{
  "assets": "/opt/libero/libero/libero/assets",
  "bddl_files": "/opt/libero/libero/libero/bddl_files",
  "benchmark_root": "/opt/libero/libero/libero",
  "datasets": "/opt/libero/libero/datasets",
  "init_states": "/opt/libero/libero/libero/init_files"
}
