<?xml version="1.0"?>
<package format="3">
  <name>silly_turtlebot_sim</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic furnished-home bringup for Silly TurtleBot.</description>
  <maintainer email="admin@robium.ai">robium</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>compressed_image_transport</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>irobot_create_description</exec_depend>
  <exec_depend>irobot_create_gz_bringup</exec_depend>
  <exec_depend>irobot_create_gz_plugins</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>silly_turtlebot_ros</exec_depend>
  <exec_depend>turtlebot4_description</exec_depend>
  <exec_depend>turtlebot4_gz_bringup</exec_depend>
  <exec_depend>turtlebot4_gz_gui_plugins</exec_depend>
  <exec_depend>turtlebot4_navigation</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
